### ISSUE TITLE
Program does not load

### ISSUE THREAD

**Issue by budgetgerman** [Universite-Gustave-Eiffel/I-Simpa#334]
Hello to all
I think you have been doing a lot of simulations. From one moment to another I can no longer run the software, when I want to do it, the screen gets stuck in loading the project, XML files. Does anyone know how to solve this problem?
Thanks!

**Comment by nicolas-f** [comment]
Hi,

Close I-Simpa then in the file explorer type the following address:

%APPDATA%

In this folder you will find the I-Simpa folder. You can move it elsewhere in order to start later I-Simpa from an empty project.

Then you can load your .proj file.

**Comment by Coarist** [comment]
Hi,

I-SIMPA program now loads correctly on my computer by following nicolas-f's posting above - by removing "isimpa" folder from %APPDATA%. 

Thanks.

**Comment by nicolas-f** [comment]
Good ^^ Thanks for feedback
