### ISSUE TITLE
Warning: point #27 is coincident with #108. Ignored

### ISSUE THREAD

**Issue by Rmgg1** [Universite-Gustave-Eiffel/I-Simpa#370]
Im doing a school assignment wherein we are tasked to examine a partition wall within 2 rooms. When adding the planes for the windows and the doors, the error of this kind appears when meshing.

![image](https://github.com/Universite-Gustave-Eiffel/I-Simpa/assets/148452754/514f5f1e-524c-465f-8f77-83cf5d87b7db)

**Comment by nicolas-f** [comment]
Hi,

This is only a warning. It just means that points has been merged. You can check final result in mesh preview ![image](https://github.com/Universite-Gustave-Eiffel/I-Simpa/assets/1382241/dc2486c6-689b-4536-a1d5-28275a1451a1)
 
https://i-simpa-wiki.readthedocs.io/fr/latest/toolbars.html#toolbar-meshing
